# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v7
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Set executable permissions
      run: |
        chmod 777 /home/runner/work/MWOProjekt/MWOProjekt/LibraryWebAppMVC.Tests/bin/Debug/net6.0
        chmod 777 /home/runner/work/MWOProjekt/MWOProjekt/LibraryWebAppMVC.Tests/bin/Debug/net6.0/selenium-manager/linux/selenium-manager
    - name: Test
      run: dotnet test --verbosity normal
